.
.TH "BCFG2\-SERVER" "8" "August 2012" "" ""
.
.SH "NAME"
\fBbcfg2\-server\fR \- Server for client configuration specifications
.
.SH "SYNOPSIS"
\fBbcfg2\-server\fR [\-d] [\-v] [\-C \fIconfigfile\fR] [\-D \fIpidfile\fR] [\-E \fIencoding\fR] [\-Q \fIrepo path\fR] [\-S \fIserver url\fR] [\-o \fIlogfile\fR] [\-x \fIpassword\fR] [\-\-ssl\-key=\fIssl key\fR]
.
.SH "DESCRIPTION"
\fBbcfg2\-server\fR is the daemon component of Bcfg2 which serves configurations to clients based on the data in its repository\.
.
.SH "OPTIONS"
.
.TP
\fB\-C\fR \fIconfigfile\fR
Specify alternate bcfg2\.conf location\.
.
.TP
\fB\-D\fR \fIpidfile\fR
Daemonize, placing the program pid in the specified pidfile\.
.
.TP
\fB\-E\fR \fIencoding\fR
Specify alternate encoding (default is UTF\-8)\.
.
.TP
\fB\-Q\fR \fIrepo path\fR
Set repository path\.
.
.TP
\fB\-S\fR \fIserver url\fR
Set server address\.
.
.TP
\fB\-d\fR
Run \fBbcfg2\-server\fR in debug mode\.
.
.TP
\fB\-v\fR
Run \fBbcfg2\-server\fR in verbose mode\.
.
.TP
\fB\-\-ssl\-key=\fR\fIssl key\fR
Set path to SSL key\.
.
.SH "SEE ALSO"
bcfg2(1), bcfg2\-lint(8)
