.TH "bcfg2-admin" 8
.SH NAME
bcfg2-admin \- Perform repository administration tasks
.SH SYNOPSIS
.B bcfg2-admin
.I init
.I client <action> <client>
.I query [g=group] [p=profile] [-f output-file] [-n] [-c]
.I compare <old> <new>
.I minestruct <client> [-g groups] [-f output-file]
.I pull <client> <entry type> <entry name>
.I tidy
.I viz [-h] [-b] [-k] [-o output.png] [-r]

.SH DESCRIPTION
.PP
.B bcfg2-admin
Perform bcfg2 repository administration
.SH MODES
.PP 
.B init
.RS
Initialize a new repository (interactive)
.RE
.B client
.RS
Add or remove clients from metadata
.RE
.B query
.RS
Search for clients based on group or profile
.RE
.B compare
.RS
Compare two client configurations. Can be used to verify consistent
behavior between releases
.RE
.B minestruct
.RS
Build structure entries based on client statistics extra entries
.RE
.B pull
.RS
Install configuration information into repo based on client bad
entries
.RE
.B tidy
.RS
Remove unused files from repository
.RE
.B viz
.RS
Create a graphviz diagram of client, group and bundle information
.RE
.SH VIZ OPTIONS
.PP
.B \-h
.RS
Include hosts in diagram
.RE
.B \-b
.RS
Include bundles in diagram
.RE
.B "-o <output file>"
.RS
Write to outfile file instead of stdout
.RE
.B \-r
.RS
Produce raw graphviz output
.RE
.B \-k
.RS
Add a shape/color key
.RE
