.
.TH "BCFG2\-LINT\.CONF" "5" "October 2012" "" ""
.
.SH "NAME"
\fBbcfg2\-lint\.conf\fR \- configuration parameters for bcfg2\-lint
.
.SH "DESCRIPTION"
\fBbcfg2\-lint\.conf\fR includes configuration parameters for \fBbcfg2\-lint\fR\.
.
.SH "FILE FORMAT"
The file is INI\-style and consists of sections and options\. A section begins with the name of the sections in square brackets and continues until the next section begins\.
.
.P
Options are specified in the form "name=value"\.
.
.P
The file is line\-based each newline\-terminated line represents either a comment, a section name or an option\.
.
.P
Any line beginning with a hash (#) is ignored, as are lines containing only whitespace\.
.
.P
The file consists of one \fB[lint]\fR section, up to one \fB[errors]\fR section, and then any number of plugin\-specific sections, documented below\. (Note that this makes it quite feasible to combine your \fBbcfg2\-lint\.conf\fR into your \fBbcfg2\.conf\fR(5) file, if you so desire)\.
.
.SH "GLOBAL OPTIONS"
These options apply to \fBbcfg2\-lint\fR generally, and must be in the \fB[lint]\fR section\.
.
.TP
\fBplugins\fR
A comma\-delimited list of plugins to run\. By default, all plugins are run\. This can be overridden by listing plugins on the command line\. See \fBbcfg2\-lint\fR(8) for a list of the available plugins\.
.
.SH "ERROR HANDLING"
Error handling is configured in the \fB[errors]\fR section\. Each option should be the name of an error and one of \fIerror\fR, \fIwarning\fR, or \fIsilent\fR, which tells \fBbcfg2\-lint\fR(8) how to handle the warning\. Error names and their defaults can be displayed by running \fBbcfg2\-lint\fR(8) with the \fB\-\-list\-errors\fR option\.
.
.SH "PLUGIN OPTIONS"
These options apply only to a single plugin\. Each option should be in a section named for its plugin; for instance, options for the InfoXML plugin would be in a section called \fB[InfoXML]\fR\.
.
.P
If a plugin is not listed below, then it has no configuration\.
.
.P
In many cases, the behavior of a plugin can be configured by modifying how errors from it are handled\. See \fI\fBERROR HANDLING\fR\fR, above\.
.
.SS "Comments"
The \fBComments\fR plugin configuration specifies which VCS keywords and comments are required for which file types\. The valid types of file are \fIglobal\fR (all file types), \fIbundler\fR (non\-templated bundle files), \fIsgenshi\fR (templated bundle files), \fIproperties\fR (property files), \fIcfg\fR (non\-templated Cfg files), \fItgenshi\fR (templated Cfg files), \fIinfoxml\fR (info\.xml files), and \fIprobe\fR (probe files)\.
.
.P
The specific types (i\.e\., types other than "global") all supplement global; they do not override it\. The exception is if you specify an empty option, e\.g\.:
.
.P
cfg_keywords =
.
.P
By default, the \fI$Id$\fR keyword is checked for and nothing else\.
.
.P
Multiple keywords or comments should be comma\-delimited\.
.
.P
· \fB<type>_keywords\fR
.
.P
Ensure that files of the specified type have the given VCS keyword\. Do \fInot\fR include the dollar signs\. I\.e\.:
.
.P
infoxml_keywords = Revision
.
.P
\fInot\fR:
.
.P
infoxml_keywords = $Revision$
.
.P
\fB· <type>_comments\fR
.
.P
Ensure that files of the specified type have a comment containing the given string\. In XML files, only comments are checked\. In plain text files, all lines are checked since comment characters may vary\.
.
.SS "InfoXML"
.
.TP
\fBrequired_attrs\fR
A comma\-delimited list of attributes to require on \fB<Info>\fR tags\. Default is "owner,group,mode"\.
.
.SS "MergeFiles"
.
.TP
\fBthreshold\fR
The threshold at which MergeFiles will suggest merging config files and probes\. Default is 75% similar\.
.
.SS "Validate"
.
.TP
\fBschema\fR
The full path to the XML Schema files\. Default is \fB/usr/share/bcfg2/schema\fR\. This can be overridden with the \fI\-\-schema\fR command\-line option
.
.SH "SEE ALSO"
bcfg2\-lint(8)
