.TH "Bcfg2debug" 8
.SH NAME
Bcfg2debug \- Debugging environment for Bcfg2
.SH SYNOPSIS
.B Bcfg2debug
.SH DESCRIPTION
.PP
.B Bcfg2debug
Instantiate an instance of the Bcfg2 core for data examination and
debugging purposes.
.SH "SEE ALSO"
.BR bcfg(1),
.BR Bcfg2Server(8)
.SH "BUGS"
None currently known