.
.TH "BCFG2\-REPORTS" "8" "August 2012" "" ""
.
.SH "NAME"
\fBbcfg2\-reports\fR \- Query reporting system for client status
.
.SH "SYNOPSIS"
\fBbcfg2\-reports\fR [\-a] [\-b \fINAME\fR] [\-c] [\-d] [\-e \fINAME\fR] [\-h] [\-m \fINAME\fR] [\-s \fINAME\fR] [\-x \fINAME\fR] [\-\-badentry=\fIKIND,NAME\fR] [\-\-extraentry=\fIKIND,NAME\fR] [\-\-fields=<ARG1,ARG2,\.\.\.>] [\-\-modifiedentry=\fIKIND,NAME\fR] [\-\-sort=<ARG1,ARG2,\.\.\.>] [\-\-stale] [\-v]
.
.SH "DESCRIPTION"
\fBbcfg2\-reports\fR allows you to retrieve data from the database about clients, and the states of their current interactions\. It also allows you to change the expired/unexpired states\. The utility runs as a standalone application\. It does, however, use the models from \fB/src/lib/Server/Reports/reports/models\.py\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-a\fR
Specify alternate bcfg2\.conf location
.
.TP
\fB\-b\fR \fIhostname\fR
Single host mode \- shows bad entries from the current interaction of \fIhostname\fR\.
.
.TP
\fB\-c\fR
Shows only clean hosts\.
.
.TP
\fB\-d\fR
Shows only dirty hosts\.
.
.TP
\fB\-e\fR \fIhostname\fR
Single host mode \- shows extra entries from the current interaction of \fIhostname\fR\.
.
.TP
\fB\-h\fR
Shows help and usage info about \fBbcfg2\-reports\fR\.
.
.TP
\fB\-m\fR \fIhostname\fR
Single host mode \- shows modified entries from the current interaction of \fIhostname\fR\.
.
.TP
\fB\-s\fR \fIhostname\fR
Single host mode \- shows bad, modified, and extra entries from the current interaction of \fIhostname\fR\.
.
.TP
\fB\-x\fR \fIhostname\fR
Toggles expired/unexpired state of \fIhostname\fR\.
.
.TP
\fB\-\-badentry=\fR\fIentry type, entry name\fR
Shows only hosts whose current interaction has bad entries of type \fIentry type\fR and name \fIentry name\fR\. If a single argument ARG1 is given, then \fIentry type\fR,\fIentry name\fR pairs will be read from a file of name ARG1\.
.
.TP
\fB\-\-extraentry=\fR\fIentry type, entry name\fR
Shows only hosts whose current interaction has extra entries of type \fIentry type\fR and name \fIentry name\fR\. If a single argument ARG1 is given, then \fIentry type\fR,\fIentry name\fR pairs will be read from a file of name ARG1\.
.
.TP
\fB\-\-fields=\fR<ARG1,ARG2,\.\.\.>
Only displays the fields \fIARG1,ARG2,\.\.\.\fR (name, time, state, total, good, bad)\.
.
.TP
\fB\-\-modifiedentry=\fR\fIentry type, entry name\fR
Shows only hosts whose current interaction has modified entries of type \fIentry type\fR and name \fIentry name\fR\. If a single argument ARG1 is given, then \fIentry type\fR,\fIentry name\fR pairs will be read from a file of name ARG1\.
.
.TP
\fB\-\-sort=\fR<ARG1,ARG2,\.\.\.>
Sorts output on ARG1,ARG2,\.\.\. (name, time, state, total, good, bad)\.
.
.TP
\fB\-\-stale\fR
Shows hosts which haven’t run in the last 24 hours\.
.
.SH "SEE ALSO"
bcfg2(1), bcfg2\-server(8)
