.TH "bcfg2" 1
.SH NAME
bcfg \- reconfigure machine based on settings in BCFG2
.SH SYNOPSIS
.B bcfg2
.I [-d] [-v] [-p] [-c cache file] [-e] [-f config file] [-I] [-q] [-b bundle]
[-r removal mode]
.SH DESCRIPTION
.PP
.B bcfg2
Runs the bcfg2 configuration process on the current host. This process
consists of first fetching and executing probes, uploading probe
results, fetching the client configuration, checking the current
client state, attempting to install the desired configuration, and
finally uploading statistics about the bcfg2 execution and client
state.
.SH OPTIONS
.PP
.B "\-d" 
.RS
Run bcfg2 in debug mode.
.RE 
.B "\-v"
.RS
Run bcfg2 in verbose mode.
.RE
.B "\-b <bundle>"
.RS
Run bcfg2 against only one bundle in the configuration. 
.RE
.B "\-P" 
.RS
Run bcfg2 in paranoid mode. Diffs will be logged for
configuration files marked as paranoid by the Bcfg2 server.
.RE
.B "\-q"
.RS
Run bcfg2 in quick mode. Package checksum verification won't be
performed. This mode relaxes the constraints of correctness, and thus
should only be used in safe conditions. 
.RE
.B "\-D <driver1>,<driver2>"
.RS
Specify a set of bcfg2 tool drivers.
.RE
.B "\-I"
.RS
Run bcfg2 in interactive mode.  The user will be prompted before each 
change.
.RE
.B "\-n"
.RS
Run bcfg2 in dry-run mode. No changes will be made to the
system. 
.RE
.B "\-B"
.RS 
Run bcfg2 in build mode. Services aren't started, as the system
may still be in miniroot.
.RE
.B "\-r <mode>" 
.RS
Cause bcfg2 to remove extra configuration elements it detects. Mode is one of all, services, or packages. All removes all entries. Likewise, services and packages remove only the extra configuration elements of the respective type.
.RE
.B "\-p <profile>" 
.RS
Assert a profile for the current client.
.RE
.B "\-e" 
.RS
When in verbose mode, display extra entry information (temporary until
verbosity rework)
.RE
.B "\-k" 
.RS
Run in bulletproof mode. This currently only effect behavior in the
debian toolset; it calls apt-get update and clean and dpkg --configure --pending.
.RE
.SH "SEE ALSO"
.BR bcfg2-server(8),
.BR bcfg2-info(8)
.SH "BUGS"
