.TH "bcfg2-repo-validate" 8
.SH NAME
bcfg2-repo-validate \- Check Bcfg2 repository data against data schemas
.SH SYNOPSIS
.B bcfg2-repo-validate
.I [-v] [ Repository Location ] [ Schema Location ]
.SH DESCRIPTION
.PP
.B bcfg2-repo-validate
This script checks data against schemas, and it quite helpful in
finding typos or malformed data. 
.SH ARGUMENTS
.TP
.B Repository Location  - where the data repository is.
.TP 
.B Schema Location - where schemas are. (Optional).
.SH "SEE ALSO"
.BR bcfg2(1),
.BR bcfg2-server(8)
.SH "BUGS"
None currently known
