.TH "bcfg2-server" 8
.SH NAME
bcfg2-server \- Server for client configuration specifications
.SH SYNOPSIS
.B bcfg2-server
.I [-D <pidfile>] [-d] [-v] [-C <Client>]
.SH DESCRIPTION
.PP
.B bcfg2-server
This daemon serves configurations to clients based on the data in its 
repository. 
.SH OPTIONS
.PP
.B \-d 
.RS
Run bcfg2 in debug mode.
.RE
.B \-v
.RS
Run bcfg2 in verbose mode.
.RE
.B "\-C <ConfigFile Path>" 
.RS
Use an alternative path for bcfg2.conf. The default is /etc/bcfg2.conf
.RE
.B \-D 
.RS
Daemonize, placing the program pid in the specified pidfile.
.RE
.B \-o <LogFile Path>
.RS
Writes a log to the specified path.
.RE
.B \-E <encoding>
.RS
Unicode encoding of config files.
.RE
.B \-x <password>
.RS
Set server password.
.RE
.B \-S <server url>
.RS
Set server address.
.RE
.B \-Q <repo path>
.RS
Set repository path.
.RE
.B \-\-ssl\-key=<ssl key>
.RS
Set path to SSL key.
.RE
.SH "SEE ALSO"
.BR bcfg2(1),
.BR bcfg2-repo-validate(8)
.SH "BUGS"
None currently known
