.
.TH "BCFG2\-LINT" "8" "October 2012" "" ""
.
.SH "NAME"
\fBbcfg2\-lint\fR \- Check Bcfg2 specification for validity, common mistakes, and style
.
.SH "SYNOPSIS"
\fBbcfg2\-lint\fR [\fIoptions\fR] [\fIplugin\fR [\fIplugin\fR\.\.\.]]
.
.SH "DESCRIPTION"
\fBbcfg2\-lint\fR checks the Bcfg2 specification for schema validity, common mistakes, and other criteria\. It can be quite helpful in finding typos or malformed data\.
.
.P
\fBbcfg2\-lint\fR exits with a return value of 2 if errors were found, and 3 if warnings (but no errors) were found\. Any other non\-0 exit value denotes some failure in the script itself\.
.
.P
\fBbcfg2\-lint\fR is a rewrite of the older bcfg2\-repo\-validate tool\.
.
.SH "OPTIONS"
.
.TP
\fB\-C\fR \fIconfigfile\fR
Specify alternate bcfg2\.conf location\.
.
.TP
\fB\-Q\fR
Specify the server repository path\.
.
.TP
\fB\-v\fR
Be verbose\.
.
.TP
\fB\-\-lint\-config\fR
Specify path to bcfg2\-lint\.conf (default \fB/etc/bcfg2\-lint\.conf\fR)\.
.
.TP
\fB\-\-stdin\fR
Rather than operating on all files in the Bcfg2 specification, only validate a list of files supplied on stdin\. This mode is particularly useful in pre\-commit hooks\.
.
.IP
This makes a few assumptions:
.
.IP
Metadata files will only be checked if a valid chain of XIncludes can be followed all the way from clients\.xml or groups\.xml\. Since there are multiple formats of metadata stored in Metadata/ (i\.e\., clients and groups), there is no way to determine which sort of data a file contains unless there is a valid chain of XIncludes\. It may be useful to always specify all metadata files should be checked, even if not all of them have changed\.
.
.IP
Property files will only be validated if both the property file itself and its matching schema are included on stdin\.
.
.TP
\fBrequire\-schema\fR
Require property files to have matching schema files\.
.
.SH "PLUGINS"
See \fBbcfg2\-lint\.conf\fR(5) for more information on the configuration of the plugins listed below\.
.
.TP
\fBBundles\fR
Check the specification for several issues with Bundler: bundles referenced in metadata but not found in \fBBundler/\fR; bundles whose \fIname\fR attribute does not match the filename; and Genshi template bundles that use the \fI\fIGroup\fR\fR tag (which is not processed in templated bundles)\.
.
.TP
\fBComments\fR
Check the specification for VCS keywords and any comments that are required\. By default, this only checks that the \fI$Id$\fR keyword is included and expanded in all files\. You may specify VCS keywords to check and comments to be required in the config file\. (For instance, you might require that every file have a "Maintainer" comment\.)
.
.IP
In XML files, only comments are checked for the keywords and comments required\.
.
.TP
\fBDuplicates\fR
Check for several types of duplicates in the Metadata: duplicate groups; duplicate clients; and multiple default groups\.
.
.TP
\fBInfoXML\fR
Check that certain attributes are specified in \fBinfo\.xml\fR files\. By default, requires that \fIowner\fR, \fIgroup\fR, and \fImode\fR are specified\. Can also require that an \fBinfo\.xml\fR exists for all Cfg files, and that paranoid mode be enabled for all files\.
.
.TP
\fBMergeFiles\fR
Suggest that similar probes and config files be merged into single probes or TGenshi templates\.
.
.TP
\fBPkgmgr\fR
Check for duplicate packages specified in Pkgmgr\.
.
.TP
\fBRequiredAttrs\fR
Check that all \fIPath\fR and \fIBoundPath\fR tags have the attributes that are required by their type (e\.g\., a path of type symlink must have name and to specified to be valid)\. This sort of validation is beyond the scope of an XML schema\.
.
.TP
\fBValidate\fR
Validate the Bcfg2 specification against the XML schemas\.
.
.IP
Property files are freeform XML, but if a \fB\.xsd\fR file with a matching filename is provided, then schema validation will be performed on property files individually as well\. For instance, if you have a property file named \fBntp\.xml\fR then by placing a schema for that file in \fBntp\.xsd\fR schema validation will be performed on \fBntp\.xml\fR\.
.
.SH "BUGS"
\fBbcfg2\-lint\fR may not handle some older plugins as well as it handles newer ones\. For instance, there may be some places where it expects all of your configuration files to be handled by Cfg rather than by a mix of Cfg and TGenshi or TCheetah\.
.
.SH "SEE ALSO"
bcfg2(1), bcfg2\-server(8), bcfg2\-lint\.conf(5)
