.TH "bcfg2-build-reports" 8
.SH NAME
bcfg2-build-reports \- Generate state reports for bcfg2 clients
.SH SYNOPSIS
.B bcfg2-build-reports
.SH DESCRIPTION
.PP
.B bcfg2-build-reports
Build all client state reports. See the Bcfg2 manual for report setup information.
.SH OPTIONS
.PP
.B \-c <configuration file>
.RS
Specify an alternate report configuration path. The default is repo/etc/reports-configuration.xml
.RE
.B \-h
.RS
Produce a help message
.RE
.B "\-s <statistics Path>"
.RS
Use an alternative path for the statistics file. The default is repo/etc/statistics.xml
.RE
.SH "SEE ALSO"
.BR bcfg(1),
.BR bcfg2-server(8)
.SH "BUGS"
None currently known
