.TH "bcfg2-query" 8
.SH NAME
bcfg2-query \- Print client names by characteristic
.SH SYNOPSIS
.B bcfg2-query        
.I [\-g group]
.I [\-p profile]
.I [\-a]

.SH DESCRIPTION
.PP
.B bcfg2-query
bcfg2-query produces streams of newline delimited client names based
on client characteristics. 
.SH OPTIONS
.PP
.B "\-a"
.RS
Display all clients
.RE
.B "\-c"
.RS
Displays nodes in a comma delimited list
.RE
.B "\-s"
.RS
Display nodes in a space delimited list
.RE
.B "\-n"
.RS
Display nodes in a newline delimited list
.RE
.B "\-v"
.RS
Turns on debugging
.RE
.B "\-p <profile>"
.RS
Display all clients that are a part of the specified profile
.RE
.B "\-g <group>"
.RS
Display all clients that are members of the specified group
.RE
.SH "SEE ALSO"
.BR bcfg2(1),
.BR bcfg2-server(8)
.SH "BUGS"
None currently known
