.
.TH "BCFG2\-BUILD\-REPORTS" "8" "June 2012" "" ""
.
.SH "NAME"
\fBbcfg2\-build\-reports\fR \- Generate state reports for Bcfg2 clients
.
.SH "SYNOPSIS"
\fBbcfg2\-build\-reports\fR [\fI\-A\fR] [\fI\-c\fR] [\fI\-s\fR] [\fI\-N\fR]
.
.SH "DESCRIPTION"
\fBbcfg2\-build\-reports\fR is used to build all client state reports\. See the Bcfg2 manual for report setup information\.
.
.SH "OPTIONS"
.
.TP
\fB\-A\fR
Displays all data\.
.
.TP
\fB\-c\fR \fIconfiguration file\fR
Specify an alternate report configuration path\. The default is repo/etc/reports\-configuration\.xml\.
.
.TP
\fB\-h\fR
Produce a help message\.
.
.TP
\fB\-s\fR \fIstatistics path\fR
Use an alternative path for the statistics file\. The default is repo/etc/statistics\.xml\.
.
.TP
\fB\-N\fR
No pinging\.
.
.SH "SEE ALSO"
bcfg2(1), bcfg2\-server(8)
