.
.TH "BCFG2\-PING\-SWEEP" "8" "June 2012" "" ""
.
.SH "NAME"
\fBbcfg2\-ping\-sweep\fR \- Update pingable and pingtime attributes in clients\.xml
.
.SH "SYNOPSIS"
\fBbcfg2\-ping\-sweep\fR
.
.SH "DESCRIPTION"
\fBbcfg2\-ping\-sweep\fR traverses the list of clients in Metadata/clients\.xml and updates their pingable/pingtime attributes\. The pingtime value is set to the last time the client was pinged (not the RTT value)\.
.
.SH "SEE ALSO"
bcfg2(1), bcfg2\-server(8)
