.
.TH "BCFG2" "1" "August 2012" "" ""
.
.SH "NAME"
\fBbcfg2\fR \- Bcfg2 client tool
.
.SH "SYNOPSIS"
\fBbcfg2\fR [\fIoptions\fR][\fI\.\.\.\fR]
.
.SH "DESCRIPTION"
\fBbcfg2\fR runs the Bcfg2 configuration process on the current host\. This process consists of the following steps\.
.
.IP "\(bu" 4
Fetch and execute probes
.
.IP "\(bu" 4
Upload probe results
.
.IP "\(bu" 4
Fetch the client configuration
.
.IP "\(bu" 4
Check the current client state
.
.IP "\(bu" 4
Attempt to install the desired configuration
.
.IP "\(bu" 4
Upload statistics about the Bcfg2 execution and client state
.
.IP "" 0
.
.SH "OPTIONS"
.
.TP
\fB\-B\fR
Configure everything except the given bundle(s)\.
.
.TP
\fB\-C\fR \fIconfigfile\fR
Specify alternate bcfg2\.conf location\.
.
.TP
\fB\-D\fR [\fIdriver1\fR,\fIdriver2\fR]
Specify a set of Bcfg2 tool drivers\.
.
.IP
\fINOTE: only drivers listed will be loaded\. (e\.g\., if you do not include POSIX, you will be unable to verify/install Path entries)\.\fR
.
.TP
\fB\-E\fR \fIencoding\fR
Specify the encoding of Cfg files\.
.
.TP
\fB\-I\fR
Run bcfg2 in interactive mode\. The user will be prompted before each change\.
.
.TP
\fB\-O\fR
Omit lock check\.
.
.TP
\fB\-P\fR
Run bcfg2 in paranoid mode\. Diffs will be logged for configuration files marked as paranoid by the Bcfg2 server\.
.
.TP
\fB\-R\fR \fIretry count\fR
Specify the number of times that the client will attempt to retry network communication\.
.
.TP
\fB\-S\fR \fIhttps://server:port\fR
Manually specify the server location (as opposed to using the value in bcfg2\.conf)\.
.
.TP
\fB\-Z\fR
Do not configure independent entries\.
.
.TP
\fB\-b\fR [\fIbundle1:bundle2\fR]
Run bcfg2 against one or multiple bundles in the configuration\.
.
.TP
\fB\-c\fR \fIcachefile\fR
Cache a copy of the configuration in cachefile\.
.
.TP
\fB\-\-ca\-cert=\fR\fIca cert\fR
Specifiy the path to the SSL CA certificate\.
.
.TP
\fB\-d\fR
Run bcfg2 in debug mode\.
.
.TP
\fB\-e\fR
When in verbose mode, display extra entry information (temporary until verbosity rework)\.
.
.TP
\fB\-f\fR \fIspecification path\fR
Configure from a file rather than querying the server\.
.
.TP
\fB\-h\fR
Print Usage information\.
.
.TP
\fB\-k\fR
Run in bulletproof mode\. This currently only affects behavior in the debian toolset; it calls apt\-get update and clean and dpkg \-\-configure \-\-pending\.
.
.TP
\fB\-l\fR \fIwhitelist|blacklist|none\fR
Run the client in the server decision list mode (unless "none" is specified, which can be done in order to override the decision list mode specified in bcfg2\.conf)\. This approach is needed when particular changes are deemed "high risk"\. It gives the ability to centrally specify these changes, but only install them on clients when administrator supervision is available\. Because collaborative configuration is one of the remaining hard issues in configuration management, these issues typically crop up in environments with several administrators and much configuration variety\. (This setting will be ignored if the \-f option is also specified)\.
.
.TP
\fB\-n\fR
Run bcfg2 in dry\-run mode\. No changes will be made to the system\.
.
.TP
\fB\-o\fR \fIlogfile path\fR
Writes a log to the specified path\.
.
.TP
\fB\-p\fR \fIprofile\fR
Assert a profile for the current client\.
.
.TP
\fB\-q\fR
Run bcfg2 in quick mode\. Package checksum verification won’t be performed\. This mode relaxes the constraints of correctness, and thus should only be used in safe conditions\.
.
.TP
\fB\-Q\fR
Run bcfg2 in "bundle quick" mode, where only entries in a bundle are verified or installed\. This runs much faster than \-q, but doesn’t provide statistics to the server at all\. In order for this option to work, the \-b option must also be provided\. This option is incompatible with \-r\.
.
.TP
\fB\-r\fR \fImode\fR
Cause bcfg2 to remove extra configuration elements it detects\. Mode is one of all, Services, or Packages\. All removes all entries\. Likewise, Services and Packages remove only the extra configuration elements of the respective type\.
.
.TP
\fB\-s\fR \fIservice mode\fR
Set bcfg2 interaction level for services\. Default behavior is to modify all services affected by reconfiguration\. build mode attempts to stop all services started\. disabled suppresses all attempts to modify services\.
.
.TP
\fB\-\-ssl\-cert=\fR\fIssl cert\fR
Specifiy the path to the SSL certificate\.
.
.TP
\fB\-\-ssl\-cns=\fR[\fICN1:CN2\fR]
List of acceptable SSL server Common Names\.
.
.TP
\fB\-\-ssl\-key=\fR\fIssl key\fR
Specifiy the path to the SSL key\.
.
.TP
\fB\-u\fR \fIuser\fR
Attempt to authenticate as ’user’\.
.
.TP
\fB\-x\fR \fIpassword\fR
Use ’password’ for client communication\.
.
.TP
\fB\-t\fR \fItimeout\fR
Set the timeout (in seconds) for client communication\. Default is 90 seconds\.
.
.TP
\fB\-v\fR
Run bcfg2 in verbose mode\.
.
.TP
\fB\-z\fR
Only configure independent entries, ignore bundles\.
.
.SH "SEE ALSO"
bcfg2\-server(8), bcfg2\-info(8)
