.TH "SummarizeStats" 8
.SH NAME
SummarizeStats \- Generate State reports for bcfg2 clients
.SH SYNOPSIS
.B SummarizeStats
.SH DESCRIPTION
.PP
.B SummarizeStats
Build all client state reports. See the Bcfg2 manual for report setup information.
.SH "SEE ALSO"
.BR bcfg(1),
.BR Bcfg2Server(8)
.SH "BUGS"
None currently known