.TH "ValidateBcfg2Repo" 8
.SH NAME
ValidateBcfg2Repo \- Check Bcfg2 repository data against data schemas
.SH SYNOPSIS
.B ValidateBcfg2Repo
.I [ Repository Location ] [ Schema Location ]
.SH DESCRIPTION
.PP
.B ValidateBcfg2Repo
This script checks data against schemas, and it quite helpful in
finding typos or malformed data. 
.SH ARGUMENTS
.TP
.B Repository Location  - where the data repository is.
.TP 
.B Schema Location - where schemas are. (Optional).
.SH "SEE ALSO"
.BR bcfg(1),
.BR Bcfg2Server(8)
.SH "BUGS"
None currently known