language: python
python:
  - "2.6"
  - "2.7"
env:
  - WITH_OPTIONAL_DEPS=yes
  - WITH_OPTIONAL_DEPS=no
install:
  - testsuite/install.sh
  - pip install --use-mirrors -e .
script:
  - nosetests testsuite
after_failure:
  - pip freeze
branches:
  except:
    - maint-1.2
    - 1.1.0-stable
notifications:
  email: chris.a.st.pierre@gmail.com
  irc:
    channels:
      - "irc.freenode.org#bcfg2"
    use_notice: true
