os: linux
arch: amd64
dist: bionic
language: python

jobs:
  include:
    - env: PYTHON=2.4 NOSE_EXCLUDE_DIRS=testsuite/Testsrc/Testlib/TestServer
      addons:
        apt:
          sources: [deadsnakes]
          packages: [python2.4, python2.4-dev]
    - env: PYTHON=2.5 NOSE_EXCLUDE_DIRS=testsuite/Testsrc/Testlib/TestServer
      addons:
        apt:
          sources: [deadsnakes]
          packages: [python2.5, python2.5-dev, libbluetooth-dev]
    - env: PYTHON=2.6 NOSE_EXCLUDE_DIRS=testsuite/Testsrc/Testlib/TestServer
      addons:
        apt:
          sources: [deadsnakes]
          packages: [python2.6, python2.6-dev]

    - python: "2.7"

    - python: "2.7"
      env: WITH_OPTIONAL_DEPS=yes TEST_SPHINX=yes
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages: [yum, python-selinux, python-gamin]

    - python: "3.6"
      env: WITH_OPTIONAL_DEPS=yes

  allow_failures:
    - python: "3.6"

  fast_finish: true

before_install:
  - testsuite/prepare-python.sh
  - if test -d "$HOME/custom-virtualenv/"; then source "$HOME/custom-virtualenv/bin/activate"; fi
install:
  - testsuite/install.sh
  - pip install -e .
before_script:
  - pip freeze
script:
  - testsuite/test.sh

notifications:
  irc:
    if: branch = master
    channels:
        - "irc.freenode.org#bcfg2"
    use_notice: true

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/wheels
    - $HOME/.cache/xml

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -f $HOME/.cache/xml/catalog.xml
