language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - WITH_OPTIONAL_DEPS=yes
  - WITH_OPTIONAL_DEPS=no
matrix:
  exclude:
    - python: "3.2"
      env: WITH_OPTIONAL_DEPS=yes
    - python: "3.3"
      env: WITH_OPTIONAL_DEPS=yes
before_install:
  - testsuite/before_install.sh
install:
  - testsuite/install.sh
  - pip install --use-mirrors -e .
script:
  - nosetests testsuite
branches:
  except:
    - maint-1.2
    - 1.1.0-stable
notifications:
  email: chris.a.st.pierre@gmail.com
  irc:
    channels:
      - "irc.freenode.org#bcfg2"
    use_notice: true
