#!/bin/sh

# Note: Solaris sed(1) requires a newline from stdin
SED="sed"
#SED="/opt/csw/bin/gsed"
#SED="/usr/xpg4/bin/sed"
#SED="/usr/ucb/sed"

chomp() {
    printf "%s\n" "$1" | ${SED} 's:^\ ::g' | ${SED} 's:\ $::g'
}

cname() {
    unset CTMP1 CTMP2
    for PART in `printf "%s\n" "$1" | ${SED} 's:-:\ :g'`; do 
        if [ ! "`printf "%s\n" "$PART" | cut -c1 | ${SED} 's:[0-9]:0:g'`x" = "0x" ]; then
        CTMP1="${CTMP1} ${PART}"
        fi
    done
    CTMP2="`chomp "$CTMP1" | ${SED} 's:\ :_:g' | ${SED} 's:\+:X:g' | tr [a-z] [A-Z]`"
    printf "\$(%s)%s" "`basename "$CTMP2"`" "$2"
}

builddeps() {
    unset DEPSTMP
    for LINE in `grep "<prereq package=\"" $1 \
                 | ${SED} 's/\ //g' \
                 | awk -F\" '{print $2}'`; do 
                 DEPSTMP="${DEPSTMP} `cname $LINE $2`"
    done
    chomp "$DEPSTMP"
}

installdeps() {
    unset DEPSTMP
    for LINE in `grep "prereq pkgspec" $1 \
                 | awk '{print $4}'`; do 
                 DEPSTMP="${DEPSTMP} `cname $LINE $2`"
    done
    chomp "$DEPSTMP"
}

printf "%s : %s\n" "`cname $1 .installed`" "`builddeps $1 .installed`"
printf "%s : %s\n" "`cname $1 .packaged`" "`installdeps $1 .packaged`"

exit 0
