#!/bin/sh -e

umask 002
BASEDIR="${ENCAP_TARGET}" # Usually /usr/local
PKGDIR="${ENCAP_SOURCE}/${ENCAP_PKGNAME}" # Ususally /usr/local/encap/<pkgname>

printf "Running ${ENCAP_PKGNAME} preremove script...\n"
date

# ostiary (daemontools)
if [ -h /service/ostiary ]; then
    printf "INFO: Removing /service/ostiary...\n"
    /command/svrm /service/ostiary
fi

# bcfg2-client (daemontools)
if [ -h /service/bcfg2-client ]; then
    printf "INFO: Removing /service/bcfg2-client...\n"
    /command/svrm /service/bcfg2-client
fi

printf "Finished ${ENCAP_PKGNAME} preremove script.\n"

exit 0
