# $Id$

# Variables

PATH = /usr/local/lib/bcfg2/bin:/usr/local/bin:/usr/bin:/bin
MAKESELF = /usr/local/bin/makeself.sh

# Main

.PHONY : all clean distclean install
.SUFFIXES : 

all : 

clean :

distclean :

install :
