# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 18:52
from __future__ import unicode_literals

import Bcfg2.Server.Plugin.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataClientModel',
            fields=[
                ('hostname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=31, null=True)),
            ],
            bases=(models.Model, Bcfg2.Server.Plugin.helpers.PluginDatabaseModel),
        ),
        migrations.CreateModel(
            name='ProbesDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('probe', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(null=True)),
            ],
            bases=(models.Model, Bcfg2.Server.Plugin.helpers.PluginDatabaseModel),
        ),
        migrations.CreateModel(
            name='ProbesGroupsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
            ],
            bases=(models.Model, Bcfg2.Server.Plugin.helpers.PluginDatabaseModel),
        ),
    ]
