#!/bin/bash
#
# Remove old bcfg2 cruft
#
# ${3} is the destination volume so that this works correctly
# when being installed to volumes other than the current OS.

/bin/rm -Rvf "${3}"{SITELIBDIR}/Bcfg2*
/bin/rm -Rvf "${3}"/usr/local/bin/bcfg2*
/bin/rm -Rvf "${3}{DATADIR}/share/bcfg2"
/bin/rm -Rvf "${3}{DATADIR}/share/man/man1/bcfg2*"
/bin/rm -Rvf "${3}{DATADIR}/share/man/man5/bcfg2*"
/bin/rm -Rvf "${3}{DATADIR}/share/man/man8/bcfg2*"
