#!/usr/bin/env python
""" Helper script for the Packages plugin, used if yum library support
is enabled.  The yum libs have horrific memory leaks, so apparently
the right way to get around that in long-running processes it to have
a short-lived helper.  No, seriously -- check out the yum-updatesd
code.  It's pure madness. """

import sys
from Bcfg2.Server.Plugins.Packages.YumHelper import CLI

if __name__ == '__main__':
    sys.exit(CLI().run())
