#!/usr/bin/env python
""" Daemon that runs to collect logs from the LocalFilesystem
Reporting transport object and add them to the Reporting storage
backend """

import sys
import logging
import Bcfg2.Logger
import Bcfg2.Options
from Bcfg2.Reporting.Collector import ReportingCollector, ReportingError


def main():
    parser = Bcfg2.Options.get_parser(description="Collect Bcfg2 report data",
                                      components=[ReportingCollector])
    parser.parse()
    logger = logging.getLogger('bcfg2-report-collector')

    # run collector
    try:
        ReportingCollector().run()
    except ReportingError:
        msg = sys.exc_info()[1]
        logger.error(msg)
        raise SystemExit(1)
    except KeyboardInterrupt:
        raise SystemExit(1)


if __name__ == '__main__':
    sys.exit(main())
