#!/usr/bin/env python

'''bcfg2-repo-validate checks all xml files in Bcfg2 repos against their respective XML schemas'''
__revision__ = '$Revision$'

import glob, lxml.etree, os, sys

import Bcfg2.Options

if __name__ == '__main__':
    opts = {'repo': Bcfg2.Options.SERVER_REPOSITORY,
            'prefix': Bcfg2.Options.INSTALL_PREFIX,
            'verbose': Bcfg2.Options.VERBOSE,
            'configfile': Bcfg2.Options.CFILE}
    setup = Bcfg2.Options.OptionParser(opts)
    setup.parse(sys.argv[1:])
    verbose = setup['verbose']
    cpath = setup['configfile']
    prefix = setup['prefix']
    schemadir = "%s/share/bcfg2/schemas" % (prefix)
    os.chdir(schemadir)
    repo = setup['repo']

    filesets = {'metadata':("%s/Metadata/groups.xml", "%s/metadata.xsd"),
                'clients':("%s/Metadata/clients.xml", "%s/clients.xsd"),
                'bundle':("%s/Bundler/*.xml", "%s/bundle.xsd"),
                'pkglist':("%s/Pkgmgr/*.xml", "%s/pkglist.xsd"),
                'base':("%s/Base/*.xml", "%s/base.xsd"),
                'rules':("%s/Rules/*.xml", "%s/rules.xsd"),
                'imageinfo':("%s/etc/report-configuration.xml", "%s/report-configuration.xsd"),
                'services':("%s/Svcmgr/*.xml", "%s/services.xsd"),
                'deps':("%s/Deps/*.xml", "%s/deps.xsd")}

    failures  = 0
    for k, (spec, schemaname) in filesets.iteritems():
        try:
            schema = lxml.etree.XMLSchema(lxml.etree.parse(open(schemaname%(schemadir))))
        except:
            print "Failed to process schema %s" % (schemaname%(schemadir))
            failures = 1
            continue
        for filename in glob.glob(spec%(repo)):
            try:
                datafile = lxml.etree.parse(open(filename))
            except SyntaxError:
                print "%s ***FAILS*** to parse \t\t<----" % (filename)
                os.system("xmllint %s" % filename)
                failures = 1
                continue
            except IOError:
                print "Failed to open file %s \t\t<---" % (filename)
                failures = 1
                continue
            if schema.validate(datafile):
                if verbose:
                    print "%s checks out" % (filename)
            else:
                rc = os.system("xmllint --noout --xinclude --schema %s %s > /dev/null 2>/dev/null" % \
                               (schemaname % schemadir, filename))
                if rc:
                    failures = 1
                    print "%s ***FAILS*** to verify \t\t<----" % (filename)
                    os.system("xmllint --noout --xinclude --schema %s %s" % \
                              (schemaname % schemadir, filename))
                elif verbose:
                    print "%s checks out" % (filename)
    raise SystemExit, failures
