#!/usr/bin/env python
""" Helper script for the Packages plugin, used if yum library support
is enabled.  The yum libs have horrific memory leaks, so apparently
the right way to get around that in long-running processes it to have
a short-lived helper.  No, seriously -- check out the yum-updatesd
code.  It's pure madness. """

import os
import sys
import yum
import logging
from optparse import OptionParser
from Bcfg2.Compat import json

LOGGER = None

def get_logger(verbose=0):
    """ set up logging according to the verbose level given on the
    command line """
    global LOGGER
    if LOGGER is None:
        LOGGER = logging.getLogger(sys.argv[0])
        stderr = logging.StreamHandler()
        if verbose:
            level = logging.DEBUG
        else:
            level = logging.WARNING
        LOGGER.setLevel(level)
        LOGGER.addHandler(stderr)
        syslog = logging.handlers.SysLogHandler("/dev/log")
        syslog.setFormatter(logging.Formatter("%(name)s: %(message)s"))
        LOGGER.addHandler(syslog)
    return LOGGER

def pkg_to_tuple(package):
    """ json doesn't distinguish between tuples and lists, but yum
    does, so we convert a package in list format to one in tuple
    format """
    if isinstance(package, list):
        return tuple(package)
    else:
        return package

def pkgtup_to_string(package):
    if package[3] in ['auto', 'any']:
        return package[0]

    rv = [package[0], "-"]
    if package[2]:
        rv.extend([package[2], ':'])
    rv.extend([package[3], '-', package[4]])
    if package[1]:
        rv.extend(['.', package[1]])
    return ''.join(str(e) for e in rv)


class DepSolver(object):
    def __init__(self, cfgfile, verbose=1):
        self.cfgfile = cfgfile
        self.yumbase = yum.YumBase()
        try:
            self.yumbase.preconf.debuglevel = verbose
            self.yumbase.preconf.fn = cfgfile
            self.yumbase._getConfig()
        except AttributeError:
            self.yumbase._getConfig(cfgfile, debuglevel=verbose)
        self.logger = get_logger(verbose)

    def get_groups(self):
        try:
            return self._groups
        except AttributeError:
            return ["noarch"]

    def set_groups(self, groups):
        self._groups = set(groups).union(["noarch"])

    groups = property(get_groups, set_groups)

    def is_package(self, package):
        if isinstance(package, tuple):
            if package[1] is None and package[2] == (None, None, None):
                pkgtup = (package[0], None, None, None, None)
            elif len(package) == 5:
                pkgtup = package
        else:
            pkgtup = (package, None, None, None, None)
        return bool(self.get_package_object(pkgtup, silent=True))

    def is_virtual_package(self, package):
        return bool(self.get_provides(package, silent=True))

    def get_package_object(self, pkgtup, silent=False):
        try:
            matches = yum.packageSack.packagesNewestByName(self.yumbase.pkgSack.searchPkgTuple(pkgtup))
        except yum.Errors.PackageSackError:
            if not silent:
                self.logger.warning("Package '%s' not found" %
                                    self.get_package_name(pkgtup))
            matches = []
        except yum.Errors.RepoError:
            err = sys.exc_info()[1]
            self.logger.error("Temporary failure loading metadata for %s: %s" %
                              (self.get_package_name(pkgtup), err))
            matches = []

        pkgs = self._filter_arch(matches)
        if pkgs:
            return pkgs[0]
        else:
            return None

    def get_deps(self, package):
        pkg = self.get_package_object(package)
        deps = []
        if pkg:
            deps = set(pkg.requires)
            # filter out things the package itself provides
            deps.difference_update([dep for dep in deps
                                    if pkg.checkPrco('provides', dep)])
        else:
            self.logger.error("No package available: %s" %
                              self.get_package_name(package))
        return deps

    def get_provides(self, required, all=False, silent=False):
        if not isinstance(required, tuple):
            required = (required, None, (None, None, None))

        try:
            prov = \
                self.yumbase.whatProvides(*required).returnNewestByNameArch()
        except yum.Errors.NoMoreMirrorsRepoError:
            err = sys.exc_info()[1]
            self.logger.error("Temporary failure loading metadata for %s: %s" %
                              (self.get_package_name(required), err))
            return []

        if prov and not all:
            prov = self._filter_provides(prov)
        elif not prov and not silent:
            self.logger.error("No package provides %s" %
                              self.get_package_name(required))
        return prov

    def get_group(self, group, ptype="default"):
        if group.startswith("@"):
            group = group[1:]

        try:
            if self.yumbase.comps.has_group(group):
                group = self.yumbase.comps.return_group(group)
            else:
                self.logger.error("%s is not a valid group" % group)
                return []
        except yum.Errors.GroupsError:
            err = sys.exc_info()[1]
            self.logger.warning(err)
            return []
        
        if ptype == "default":
            return [p
                    for p, d in list(group.default_packages.items())
                    if d]
        elif ptype == "mandatory":
            return [p
                    for p, m in list(group.mandatory_packages.items())
                    if m]
        elif ptype == "optional" or ptype == "all":
            return group.packages
        else:
            self.logger.warning("Unknown group package type '%s'" % ptype)
            return []

    def _filter_provides(self, providers):
        providers = [pkg for pkg in self._filter_arch(providers)]
        if len(providers) > 1:
            # go through each provider and make sure it's the newest
            # package of its name available.  If we have multiple
            # providers, avoid installing old packages.
            #
            # For instance: on Fedora 14,
            # perl-Sub-WrapPackages-2.0-2.fc14 erroneously provided
            # perl(lib), which should not have been provided;
            # perl(lib) is provided by the "perl" package.  The bogus
            # provide was removed in perl-Sub-WrapPackages-2.0-4.fc14,
            # but if we just queried to resolve the "perl(lib)"
            # dependency, we'd get both packages.  By performing this
            # check, we learn that there's a newer
            # perl-Sub-WrapPackages available, so it can't be the best
            # provider of perl(lib).
            rv = []
            for pkg in providers:
                found = self.get_package_object(pkg.pkgtup)
                if found == pkg or found.pkgtup == pkg.pkgtup:
                    rv.append(pkg)
                else:
                    self.logger.debug("Skipping %s, not newest (%s)" %
                                      (pkg, found))
        else:
            rv = providers
        return rv

    def _filter_arch(self, packages):
        matching = []
        for pkg in packages:
            if pkg.arch in self.groups:
                matching.append(pkg)
            else:
                self.logger.debug("%s has non-matching architecture (%s)" %
                                  (pkg, pkg.arch))
        if matching:
            return matching
        else:
            # no packages match architecture; we'll assume that the
            # user knows what s/he is doing and this is a multiarch
            # box.
            return packages

    def get_package_name(self, package):
        """ get the name of a package or virtual package from the
        internal representation used by this Collection class """
        if isinstance(package, tuple):
            if len(package) == 3:
                return yum.misc.prco_tuple_to_string(package)
            else:
                return pkgtup_to_string(package)
        else:
            return str(package)

    def complete(self, packagelist):
        packages = set()
        unknown = set()
        for pkg in packagelist:
            if isinstance(pkg, tuple):
                pkgtup = pkg
            else:
                pkgtup = (pkg, None, None, None, None)
            po = self.get_package_object(pkgtup)
            if not po:
                self.logger.debug("Unknown package %s" %
                                  self.get_package_name(pkg))
                unknown.add(pkg)
            else:
                if self.yumbase.tsInfo.exists(pkgtup=po.pkgtup):
                    self.logger.debug("%s added to transaction multiple times" %
                                      po)
                else:
                    self.logger.debug("Adding %s to transaction" % po)
                    self.yumbase.tsInfo.addInstall(po)
        self.yumbase.resolveDeps()

        for txmbr in self.yumbase.tsInfo:
            packages.add(txmbr.pkgtup)
        return list(packages), list(unknown)

    def clean_cache(self):
        for mdtype in ["Headers", "Packages", "Sqlite", "Metadata",
                       "ExpireCache"]:
            # for reasons that are entirely obvious, all of the yum
            # API clean* methods return a tuple of 0 (zero, always
            # zero) and a list containing a single message about how
            # many files were deleted.  so useful.  thanks, yum.
            msg = getattr(self.yumbase, "clean%s" % mdtype)()[1][0]
            if not msg.startswith("0 "):
                self.logger.info(msg)


def main():
    parser = OptionParser()
    parser.add_option("-c", "--config", help="Config file")
    parser.add_option("-v", "--verbose", help="Verbosity level", action="count")
    (options, args) = parser.parse_args()
    logger = get_logger(options.verbose)
    try:
        cmd = args[0]
    except IndexError:
        logger.error("No command given")
        return 1

    if not os.path.exists(options.config):
        logger.error("Config file %s not found" % options.config)
        return 1

    depsolver = DepSolver(options.config, options.verbose)
    if cmd == "clean":
        depsolver.clean_cache()
        print(json.dumps(True))
    elif cmd == "complete":
        data = json.loads(sys.stdin.read())
        depsolver.groups = data['groups']
        (packages, unknown) = depsolver.complete([pkg_to_tuple(p)
                                                  for p in data['packages']])
        print(json.dumps(dict(packages=list(packages),
                              unknown=list(unknown))))
    elif cmd == "is_virtual_package":
        package = pkg_to_tuple(json.loads(sys.stdin.read()))
        print(json.dumps(bool(depsolver.get_provides(package, silent=True))))
    elif cmd == "get_deps" or cmd == "get_provides":
        package = pkg_to_tuple(json.loads(sys.stdin.read()))
        print(json.dumps([p.name for p in getattr(depsolver, cmd)(package)]))
    elif cmd == "get_group":
        data = json.loads(sys.stdin.read())
        if "type" in data:
            packages = depsolver.get_group(data['group'], ptype=data['type'])
        else:
            packages = depsolver.get_group(data['group'])
        print(json.dumps(list(packages)))
    elif cmd == "get_groups":
        data = json.loads(sys.stdin.read())
        rv = dict()
        for gdata in data:
            if "type" in gdata:
                packages = depsolver.get_group(gdata['group'],
                                               ptype=gdata['type'])
            else:
                packages = depsolver.get_group(gdata['group'])
            rv[gdata['group']] = list(packages)
        print(json.dumps(rv))
    elif cmd == "is_package":
        package = pkg_to_tuple(json.loads(sys.stdin.read()))
        print(json.dumps(getattr(depsolver, cmd)(package)))
        
        
if __name__ == '__main__':
    sys.exit(main())
