#!/usr/bin/env python
""" bcfg2-admin is a script that helps to administer a Bcfg2
deployment. """

import sys
from Bcfg2.Server.Admin import CLI

if __name__ == '__main__':
    try:
        sys.exit(CLI().run())
    except KeyboardInterrupt:
        raise SystemExit(1)
