#!/usr/bin/env python
# Jul 17 2005
#GenerateHostInfo - Joey Hagedorn - hagedorn@mcs.anl.gov

'''Generates hostinfo.xml at a regular interval'''
__revision__ = '$Revision$'

from ConfigParser import ConfigParser
from elementtree.ElementTree import Element, SubElement, parse
from os import system, fork, execl, dup2, wait
import sys

def pretty_print(element, level=0):
    '''Produce a pretty-printed text representation of element'''
    if element.text:
        fmt = "%s<%%s %%s>%%s</%%s>" % (level*" ")
        data = (element.tag, (" ".join(["%s='%s'" % keyval for keyval in element.attrib.iteritems()])),
                element.text, element.tag)
    if element._children:
        fmt = "%s<%%s %%s>\n" % (level*" ",) + (len(element._children) * "%s") + "%s</%%s>\n" % (level*" ")
        data = (element.tag, ) + (" ".join(["%s='%s'" % keyval for keyval in element.attrib.iteritems()]),)
        data += tuple([pretty_print(entry, level+2) for entry in element._children]) + (element.tag, )
    else:
        fmt = "%s<%%s %%s/>\n" % (level * " ")
        data = (element.tag, " ".join(["%s='%s'" % keyval for keyval in element.attrib.iteritems()]))
    return fmt % data

                                                                                                                
if __name__ == '__main__':
    c = ConfigParser()
    c.read(['/etc/bcfg2.conf'])
    hostinfopath = "%s/hostinfo.xml" % c.get('server', 'metadata')
    metadatapath = "%s/metadata.xml" % c.get('server', 'metadata')
    configpath = "%s/report-configuration.xml" % c.get('server', 'metadata')
    domainlist = c.get('statistics', 'domainlist').replace("\'","").split(",")
    sendmailpath = c.get('statistics','sendmailpath')
    
    metaElement =  parse(metadatapath)
    hostlist = [client.get('name') for client in metaElement.findall("Client")]

    HostInfo = Element("HostInformation")
    pids = {}
    fullnames = {}
    null = open('/dev/null', 'w+')
    while hostlist or pids:
        if hostlist and len(pids.keys()) < 15:
            host = hostlist.pop()
            pid = fork()
            if pid == 0:
                # in child
                dup2(null.fileno(), sys.__stdin__.fileno())
                dup2(null.fileno(), sys.__stdout__.fileno())
                dup2(null.fileno(), sys.__stderr__.fileno())
                execl('/bin/ping', 'ping', '-W', '5', '-c', '1', host)
            else:
                pids[pid] = host
        else:
            try:
                (cpid, status) = wait()
                chost = pids[cpid]
                del pids[cpid]
                if status == 0:
                    SubElement(HostInfo, "HostInfo", name=chost, fqdn=chost, pingeable='Y')
                else:
                    if chost.count('.') > 0:
                        fullnames[chost.split('.')[0]] = chost
                        hostlist.append(chost.split('.')[0])
                    else:
                        SubElement(HostInfo, "HostInfo", name=fullnames[chost], fqdn=fullnames[chost], pingeable='N')
            except:
                pass

    fout = open(hostinfopath, 'w')
    fout.write(pretty_print(HostInfo))
    fout.close()
                        
